name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Измените на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create SSH directory and known_hosts file
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H 178.250.152.97 >> ~/.ssh/known_hosts
      env:
        CI_SSH_KEY: ${{ secrets.PRIVATE_KEY_PATH }} # Ваш приватный ключ SSH
        PRIVATE_KEY_PATH: ${{ secrets.PRIVATE_KEY_PATH }}
        SSH_KNOWN_HOSTS: ~/.ssh/known_hosts
    
    - name: Deploy to remote server
      run: scp -i ${{ env.PRIVATE_KEY_PATH }} -r ./ info@178.250.152.97:/home/info/web/lib2.libercode.site/public_html
