name: Копирование файлов на удаленный сервер

on:
  push:
    branches: [ main ]

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: actions/setup-ssh@v3
        with:
          ssh-key-path: ${{ secrets.PRIVATE_KEY_PATH }}
          ssh-private-key-file: github

      - name: Connect to remote server
        uses: actions/connect@v3
        with:
          server: 89.191.229.174
          user: root
          private-key-file: github

      - name: Copy files to remote server
        run: |
          scp -r /* root@89.191.229.174:/var/www/html/test
