name: Копирование файлов на удаленный сервер

on:
  push:
    branches: [ main ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.PRIVATE_KEY_PATH }} # ----- BEGIN RSA PRIVATE KEY----- ...
      - run: ssh -T git@github.com || true
  copy-files:
    runs-on: ubuntu-latest

    steps:
 
      - name: Connect to remote server
        uses: actions/connect@v3
        with:
          server: 89.191.229.174
          user: root
          private-key-file: github

      - name: Copy files to remote server
        run: |
          scp -r /* root@89.191.229.174:/var/www/html/test
